syntax = "proto3";

package kvpb;

option go_package = "raftmage/internal/clientapi/kvpb";

service KV {
  rpc Get(GetRequest) returns (GetReply);
  rpc Put(PutRequest) returns (PutReply);
  rpc Delete(DeleteRequest) returns (DeleteReply);
}

message GetRequest {
  string key = 1;
}

message GetReply {
  bytes value = 1;
}

message PutRequest {
  string key = 1;
  bytes value = 2;
}

message PutReply {
  uint64 index = 1;
}

message DeleteRequest {
  string key = 1;
}

message DeleteReply {
  uint64 index = 1;
}
